=== wesamalhaj/Strukturierter-und-wiederverwendbarer-Treiber-des-Timer-Moduls-eines-Cortex-M4F-basierten-Mikrocontr/projectConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:hawgitter="https://gitlab.tphys.jku.at/haw-hamburg/tools/haw-gitter.git"
           targetNamespace="https://gitlab.tphys.jku.at/haw-hamburg/tools/haw-gitter.git"
           elementFormDefault="qualified">

    <xs:element name="projectConfig" type="hawgitter:projectConfig"></xs:element>

    <xs:complexType name="projectConfig">
    	<xs:sequence minOccurs="1" maxOccurs="1">
    		<xs:element name="libraries" type="hawgitter:libraries" minOccurs="1" maxOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="libraries">
    	<xs:sequence minOccurs="1" maxOccurs="1">
    		<xs:element name="library" type="hawgitter:library" minOccurs="1" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="library">
    	<xs:choice minOccurs="1" maxOccurs="1">
    		<xs:element name="gitLibrary" type="hawgitter:gitLibrary"></xs:element>
    	</xs:choice>
    </xs:complexType>

    <xs:complexType name="gitLibrary">
    	<xs:sequence minOccurs="1" maxOccurs="1">
    		<xs:element name="localPath" type="xs:anyURI" minOccurs="1"
    			maxOccurs="1">
    		</xs:element>
    		<xs:element name="gitRepository" type="xs:anyURI"
    			minOccurs="1" maxOccurs="1">
    		</xs:element>
    		<xs:element name="gitReference"
    			type="hawgitter:gitReference" minOccurs="1" maxOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="gitReference">
    	<xs:choice minOccurs="1" maxOccurs="1">
    		<xs:element name="gitBranch" type="xs:string" minOccurs="1"
    			maxOccurs="1">
    		</xs:element>
    		<xs:element name="gitTag" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    	</xs:choice>
    </xs:complexType>
</xs:schema>

=== wesamalhaj/Strukturierter-und-wiederverwendbarer-Treiber-des-Timer-Moduls-eines-Cortex-M4F-basierten-Mikrocontr/projectConfig.xml
<hawgitter:projectConfig
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:hawgitter="https://gitlab.tphys.jku.at/haw-hamburg/tools/haw-gitter.git"
  xsi:schemaLocation="https://gitlab.tphys.jku.at/haw-hamburg/tools/haw-gitter.git projectConfig.xsd"
>
	<hawgitter:libraries>
		<hawgitter:library>
			<hawgitter:gitLibrary>
				<hawgitter:localPath>rtos/FreeRTOS</hawgitter:localPath>
				<hawgitter:gitRepository>https://gitlab.tphys.jku.at/haw-hamburg/embedded-c/Tiva-TM4C1294NCPDT/repos/rtos/FreeRTOS.git</hawgitter:gitRepository>
				<hawgitter:gitReference>
					<hawgitter:gitTag>FreeRTOSv10.2.1_HAWv0.1</hawgitter:gitTag>
				</hawgitter:gitReference>
			</hawgitter:gitLibrary>
		</hawgitter:library>
    <hawgitter:library>
			<hawgitter:gitLibrary>
				<hawgitter:localPath>hal/sysctl</hawgitter:localPath>
				<hawgitter:gitRepository>https://gitlab.tphys.jku.at/haw-hamburg/embedded-c/Tiva-TM4C1294NCPDT/repos/hal/sysctl.git</hawgitter:gitRepository>
				<hawgitter:gitReference>
					<hawgitter:gitBranch>devel</hawgitter:gitBranch>
				</hawgitter:gitReference>
			</hawgitter:gitLibrary>
		</hawgitter:library>
    <hawgitter:library>
			<hawgitter:gitLibrary>
				<hawgitter:localPath>hal/nvic</hawgitter:localPath>
				<hawgitter:gitRepository>https://gitlab.tphys.jku.at/haw-hamburg/embedded-c/Tiva-TM4C1294NCPDT/repos/hal/nvic.git</hawgitter:gitRepository>
				<hawgitter:gitReference>
					<hawgitter:gitBranch>devel</hawgitter:gitBranch>
				</hawgitter:gitReference>
			</hawgitter:gitLibrary>
		</hawgitter:library>
    <hawgitter:library>
			<hawgitter:gitLibrary>
				<hawgitter:localPath>hal/gpio</hawgitter:localPath>
				<hawgitter:gitRepository>https://gitlab.tphys.jku.at/haw-hamburg/embedded-c/Tiva-TM4C1294NCPDT/repos/hal/gpio.git</hawgitter:gitRepository>
				<hawgitter:gitReference>
					<hawgitter:gitBranch>devel</hawgitter:gitBranch>
				</hawgitter:gitReference>
			</hawgitter:gitLibrary>
		</hawgitter:library>
    <hawgitter:library>
			<hawgitter:gitLibrary>
				<hawgitter:localPath>hal/gptm</hawgitter:localPath>
				<hawgitter:gitRepository>https://gitlab.tphys.jku.at/haw-hamburg/embedded-c/Tiva-TM4C1294NCPDT/repos/hal/gptm.git</hawgitter:gitRepository>
				<hawgitter:gitReference>
					<hawgitter:gitBranch>devel</hawgitter:gitBranch>
				</hawgitter:gitReference>
			</hawgitter:gitLibrary>
		</hawgitter:library>
	</hawgitter:libraries>
</hawgitter:projectConfig>
