=== wesamalhaj/Strukturierter-und-wiederverwendbarer-Treiber-des-Timer-Moduls-eines-Cortex-M4F-basierten-Mikrocontr/hal/gptm/ashig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:ashig="https://gitlab.tphys.jku.at/haw-hamburg/codegen/ashig.git"
           targetNamespace="https://gitlab.tphys.jku.at/haw-hamburg/codegen/ashig.git"
           elementFormDefault="qualified">
  <xs:element name="hardwareInterface"
              type="ashig:hardwareInterface"/>
  <xs:complexType name="hardwareInterface">
    <xs:sequence minOccurs="1"
                 maxOccurs="1">
      <xs:element name="platform"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:whiteSpace value="collapse"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="manufacturer"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
        	<xs:restriction base="xs:string">
        		<xs:minLength value="1" />
        		<xs:whiteSpace value="collapse"></xs:whiteSpace>
        	</xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="targetPeripheralModule"
                  type="ashig:peripheralModule"
                  maxOccurs="1"
                  minOccurs="1">
			</xs:element>
      <xs:element name="supportingPeripheralModules"
                  type="ashig:peripheralModules"
                  maxOccurs="1"
                  minOccurs="0">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="peripheralModules">
    <xs:sequence minOccurs="1"
                 maxOccurs="1">
      <xs:element name="peripheralModule"
                  type="ashig:peripheralModule"
                  maxOccurs="unbounded"
                  minOccurs="1">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="peripheralModule">
    <xs:sequence minOccurs="1"
                 maxOccurs="1">
      <xs:element name="moduleName"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
        	<xs:restriction base="xs:string">
        		<xs:minLength value="1" />
        		<xs:whiteSpace value="collapse" />
        		<xs:pattern value="[a-zA-Z][_0-9a-zA-Z]*"></xs:pattern>
        	</xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="coreDefinition"
                  minOccurs="1"
                  maxOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="public"/>
            <xs:enumeration value="private"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="cores"
                  type="ashig:cores"
                  maxOccurs="1"
                  minOccurs="1">
			</xs:element>
      <xs:element name="registers"
                  type="ashig:registers"
                  maxOccurs="1"
                  minOccurs="1">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cores">
    <xs:sequence>
      <xs:element name="core"
                  type="ashig:core"
                  maxOccurs="unbounded"
                  minOccurs="1">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="registers">
    <xs:sequence minOccurs="1"
                 maxOccurs="1">
      <xs:element name="register"
                  type="ashig:register"
                  maxOccurs="unbounded"
                  minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="core">
    <xs:sequence>
      <xs:element name="coreName" maxOccurs="1" minOccurs="1">

      	<xs:simpleType>
      		<xs:restriction base="xs:string">
      			<xs:minLength value="1"></xs:minLength>
      			<xs:whiteSpace value="collapse"></xs:whiteSpace>
      			<xs:pattern value='[a-zA-Z][_0-9a-zA-Z]*'></xs:pattern>
      		</xs:restriction>
      	</xs:simpleType>
      </xs:element>
      <xs:element name="baseAddress"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0][x][A-F0-9]{8}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="register">
    <xs:sequence minOccurs="1"
                 maxOccurs="1">
      <xs:element name="registerName" maxOccurs="1" minOccurs="1">
      	<xs:simpleType>
      		<xs:restriction base="xs:string">
      			<xs:minLength value="1"></xs:minLength>
      			<xs:whiteSpace value="collapse"></xs:whiteSpace>
      			<xs:pattern value="[a-zA-Z][_0-9a-zA-Z]*"></xs:pattern>
      		</xs:restriction>
      	</xs:simpleType>
      </xs:element>
      <xs:element name="offset"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0][x][A-F0-9]{8}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="length"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:nonNegativeInteger">
            <xs:enumeration value="32"/>
            <xs:enumeration value="16"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fields"
                  type="ashig:fields"
                  maxOccurs="1"
                  minOccurs="1">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fields">
    <xs:sequence>
      <xs:element name="field"
                  type="ashig:field"
                  maxOccurs="unbounded"
                  minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="field">
    <xs:sequence>
      <xs:element name="fieldName" maxOccurs="1" minOccurs="1">
      	<xs:simpleType>
      		<xs:restriction base="xs:string">
      			<xs:minLength value="1"></xs:minLength>
      			<xs:pattern value="[a-zA-Z][_0-9a-zA-Z]*"></xs:pattern>
      		</xs:restriction>
      	</xs:simpleType>
      </xs:element>
      <xs:element name="fieldOffset"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
        	<xs:restriction base="xs:unsignedByte">
        		<xs:minInclusive value="0" />
        		<xs:maxInclusive value="31"></xs:maxInclusive>
        		<xs:whiteSpace value="collapse"></xs:whiteSpace>
        	</xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fieldLength"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
        	<xs:restriction base="xs:unsignedByte">
        		<xs:minInclusive value="1" />
        		<xs:maxInclusive value="32" />
        		<xs:whiteSpace value="collapse"></xs:whiteSpace>
        	</xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fieldType"
                  maxOccurs="1"
                  minOccurs="1">
        <xs:simpleType>
        	<xs:restriction base="xs:string">
        		<xs:enumeration value="RO" />
        		<xs:enumeration value="RW" />
        		<xs:enumeration value="WO" />
        		<xs:enumeration value="W1C" />
        		<xs:enumeration value="RW1C" />
        		<xs:enumeration value="-" />
        		<xs:whiteSpace value="collapse"></xs:whiteSpace>
        	</xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fieldValues"
                  type="ashig:fieldValues"
                  maxOccurs="unbounded"
                  minOccurs="0">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fieldValues">
    <xs:sequence>
      <xs:element name="fieldValue"
                  type="ashig:fieldValue"
                  maxOccurs="unbounded"
                  minOccurs="1">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fieldValue">
    <xs:sequence>
      <xs:element name="name" maxOccurs="1" minOccurs="1">
      	<xs:simpleType>
      		<xs:restriction base="xs:string">
      			<xs:minLength value="1"></xs:minLength>
      			<xs:pattern value="[a-zA-Z][_0-9a-zA-Z]*"></xs:pattern>
      			<xs:whiteSpace value="collapse"></xs:whiteSpace>
      		</xs:restriction>
      	</xs:simpleType>
      </xs:element>
      <xs:element name="value" maxOccurs="1" minOccurs="1">
      	<xs:simpleType>
      		<xs:restriction base="xs:string">
      			<xs:pattern value="[0][x][A-F0-9]{8}"></xs:pattern>
      			<xs:minLength value="1"></xs:minLength>
      			<xs:whiteSpace value="collapse"></xs:whiteSpace>
      		</xs:restriction>
      	</xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="targetPeripheralModule">
    <xs:sequence minOccurs="1"
                 maxOccurs="1">
      <xs:element name="peripheralModule"
                  type="ashig:peripheralModule"
                  maxOccurs="unbounded"
                  minOccurs="1">
			</xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== wesamalhaj/Strukturierter-und-wiederverwendbarer-Treiber-des-Timer-Moduls-eines-Cortex-M4F-basierten-Mikrocontr/hal/gptm/gptmShi.xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:hardwareInterface
	xmlns:ti="https://gitlab.tphys.jku.at/haw-hamburg/codegen/ashig.git"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://gitlab.tphys.jku.at/haw-hamburg/codegen/ashig.git ashig.xsd"
  >
	<ti:platform>TM4C1294NCPDT</ti:platform>
	<ti:manufacturer>TEXAS INSTRUMENTS</ti:manufacturer>
	<ti:targetPeripheralModule>
		<ti:moduleName>GPTM</ti:moduleName>
		<ti:coreDefinition>public</ti:coreDefinition>
		<ti:cores>
			<ti:core>
				<ti:coreName>Timer0</ti:coreName>
				<ti:baseAddress>0x40030000</ti:baseAddress>
			</ti:core>
			<ti:core>
				<ti:coreName>Timer1</ti:coreName>
				<ti:baseAddress>0x40031000</ti:baseAddress>
			</ti:core>
			<ti:core>	
				<ti:coreName>Timer2</ti:coreName>
				<ti:baseAddress>0x40032000</ti:baseAddress>
			</ti:core>
			<ti:core>	
				<ti:coreName>Timer3</ti:coreName>
				<ti:baseAddress>0x40033000</ti:baseAddress>
			</ti:core>
			<ti:core>	
				<ti:coreName>Timer4</ti:coreName>
				<ti:baseAddress>0x40034000</ti:baseAddress>
			</ti:core>
			<ti:core>	
				<ti:coreName>Timer5</ti:coreName>
				<ti:baseAddress>0x40035000</ti:baseAddress>
			</ti:core>
			<ti:core>	
				<ti:coreName>Timer6</ti:coreName>
				<ti:baseAddress>0x400E0000</ti:baseAddress>
			</ti:core>
			<ti:core>	
				<ti:coreName>Timer7</ti:coreName>
				<ti:baseAddress>0x400E1000</ti:baseAddress>
			</ti:core>
		</ti:cores>		
		<ti:registers>
		
			<ti:register>
				<ti:registerName>GPTMCFG</ti:registerName>
				<ti:offset>0x00000000</ti:offset>
				<ti:length>32</ti:length>
				<ti:fields>
					
					<ti:field>
						<ti:fieldName>GPTMCFG</ti:fieldName>
						<ti:fieldOffset>0</ti:fieldOffset>
						<ti:fieldLength>4</ti:fieldLength>
						<ti:fieldType>RW</ti:fieldType>
						<ti:fieldValues>
							<ti:fieldValue>
								<ti:name>CONFIG_16_BIT</ti:name>
								<ti:value>0x00000004</ti:value>
							</ti:fieldValue>
							<ti:fieldValue>
								<ti:name>CONFIG_32_BIT_real</ti:name>
								<ti:value>0x00000001</ti:value>
							</ti:fieldValue>
							<ti:fieldValue>
								<ti:name>CONFIG_32_BIT</ti:name>
								<ti:value>0x00000000</ti:value>
							</ti:fieldValue>
						</ti:fieldValues>
					</ti:field>
					
				</ti:fields>
			</ti:register>
			
			
			<ti:register>
				<ti:registerName>GPTMTAMR</ti:registerName>
				<ti:offset>0x00000004</ti:offset>
				<ti:length>32</ti:length>
				<ti:fields>
					
					<ti:field>
							<ti:fieldName>TAMR</ti:fieldName>
							<ti:fieldOffset>0</ti:fieldOffset>
							<ti:fieldLength>2</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>One_Shot_Timer_mode</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Periodic_Timer_mode</ti:name>
									<ti:value>0x00000002</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Capture_mode</ti:name>
									<ti:value>0x00000003</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TACMR</ti:fieldName>
							<ti:fieldOffset>2</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Edge_Count_mode</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Edge_Time_mode</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TAAMS</ti:fieldName>
							<ti:fieldOffset>3</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Capture_or_compare_mode_Enabled</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>PWM_mode_Enabled</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TACDIR</ti:fieldName>
							<ti:fieldOffset>4</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Timer_counts_down</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Timer_counts_up</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TAMIE</ti:fieldName>
							<ti:fieldOffset>5</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>match_interrupt_Disabled</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>interrupt_generated</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TAWOT</ti:fieldName>
							<ti:fieldOffset>6</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>TimerA_not_Wait_on_Trigger</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>TimerA_Wait_on_Trigger</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TASNAPS</ti:fieldName>
							<ti:fieldOffset>7</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>DISABLE_Snap_shot_mode</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>ENABLE_Snap_shot_mode</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TAILD</ti:fieldName>
							<ti:fieldOffset>8</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Update_GPTMTAR_GPTMTAV_register_on_next_cycle</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Update_GPTMTAR_GPTMTAV_register_on_next_Time_out</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TAPWMIE</ti:fieldName>
							<ti:fieldOffset>9</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>PWM_Capture_event_interrupt_disabled</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>PWM_Capture_event_interrupt_enabled</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					
					<ti:field>
							<ti:fieldName>TAMRSU</ti:fieldName>
							<ti:fieldOffset>10</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Update_GPTMTAMATCHR_GPTMTAPR_register_on_next_cycle</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Update_GPTMTAMATCHR_GPTMTAPR_register_on_next_Time_Out</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TAPLO</ti:fieldName>
							<ti:fieldOffset>11</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Output_unaffected</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Output_inverted</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
									
					<ti:field>
							<ti:fieldName>TACINTD</ti:fieldName>
							<ti:fieldOffset>12</ti:fieldOffset>
							<ti:fieldLength>1</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Time_out_interrupt_enabled</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Time_out_interrupt_disabled</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
							</ti:fieldValues>
					</ti:field>
					
					<ti:field>
							<ti:fieldName>TCACT</ti:fieldName>
							<ti:fieldOffset>13</ti:fieldOffset>
							<ti:fieldLength>3</ti:fieldLength>
							<ti:fieldType>RW</ti:fieldType>
							<ti:fieldValues>
								<ti:fieldValue>
									<ti:name>Disable_compare_operations</ti:name>
									<ti:value>0x00000000</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Toggle_State_on_Time_Out</ti:name>
									<ti:value>0x00000001</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Clear_CCP_on_Time_Out</ti:name>
									<ti:value>0x00000002</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Set_CCP_on_Time_Out</ti:name>
									<ti:value>0x00000003</ti:value>
								</ti:fieldValue>
								<ti:fieldValue>
									<ti:name>Set_CCP_immediately_and_toggle_on_Time_Out</ti:name>
